---
title: "Assignment 3 - Task 3"
author: "Chase Tarr"
date: "10/25/2021"
output: html_document
---
# Overview
```{r setup, include=TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(kableExtra)
library(palmerpenguins)

```

## Reading in the Data
 - Urchins
```{r}
urchins <- read_csv(here("data", "urchins.csv")) %>% 
  clean_names()
```

# Section 1: Size Comparisons
 - Comparing size of purple and red urchins

### Data Visualization 
```{r}
ggplot(data = urchins, aes(x = size, fill = common_name)) +
  scale_fill_manual(values = c("purple", "red"),
                    name = "Species") +
  geom_histogram(bin = 10) +
  facet_wrap(~ common_name) +
  labs(x = "Urchin Diameter (cm)", y = "Count")
  
```

### Descriptive Statistics Table
```{r}
urchins_purp_vs_red <- urchins %>% 
  group_by(common_name) %>% 
  summarize(
    mean_size_cm = round(mean(size), 2),
    sd_size_cm = round(mean(size), 2),
    median_size_cm = median(size),
    sample_size_n = n())


urchins_purp_vs_red
```

# Section 2
 - Exploring Purple Urchins by site and year
 
```{r}
purple_urchins <- urchins %>% 
  filter(common_name == "Purple Urchin") %>% 
  mutate(Date = mdy(date)) %>% 
  mutate(Year = year(Date)) %>% 
  mutate(site_new = case_when(
    site == "NAPL" ~ "Naples Reef",
    site == "AQUE" ~ "Arroyo Quemado Reef", 
    site == "CARP" ~ "Carpinteria Reef",
    site == "MOHK" ~ "Mohawk Reef",
    site == "IVEE" ~ "Isla Vista Reef")
  ) %>% 
  select(site, treatment, size, scientific_name, common_name, Date, Year, site_new)

purple_urchins_table <- purple_urchins %>% 
  group_by(site_new, Year, common_name) %>% 
  summarize(
    total_per_site =  n()
  )
```
 
## Finalized Graph

```{r}
ggplot(data = purple_urchins, aes(x = Date, fill = site_new)) +
  scale_fill_manual(values = c("purple", "red", "blue", "yellow", "orange"),
                    name = "Site")+
  geom_histogram(bin = 45) +
  facet_wrap(~ site_new, scales = 'free')+
  labs(x = "Year", y = "Purple Urchin Count")
```

 